import mock from "../mock";

const assets = [
    {
        "id": 18813404,
        "token_id": "674331",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Natasha Yi - Wild 94.9 DJ - Model",
        "description": "Natasha Yi",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674331",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/32.png",
            "address": "0x3c49f83c295b79597cb2a1820f85d8c895788775",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813403,
        "token_id": "674328",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Bean Property Writer",
        "description": "Klip snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674328",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/22.png",
            "address": "0xaa91b38a31e4b1d8955591ab040ba033449c240b",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813408,
        "token_id": "674329",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Mbappe / Vietto",
        "description": "NullAddress",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674329",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/19.png",
            "address": "0x29ab976d7cd5a5c059a747575a72e4c40572540a",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813408,
        "token_id": "674329",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Aesthetic",
        "description": "Aesthetic and beautiful young woman",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674329",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/19.png",
            "address": "0x29ab976d7cd5a5c059a747575a72e4c40572540a",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },

    {
        "id": 18813404,
        "token_id": "674331",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Natasha Yi - Wild 94.9 DJ - Model",
        "description": "Natasha Yi",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674331",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/32.png",
            "address": "0x3c49f83c295b79597cb2a1820f85d8c895788775",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813403,
        "token_id": "674328",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Bean Property Writer",
        "description": "Klip snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674328",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/22.png",
            "address": "0xaa91b38a31e4b1d8955591ab040ba033449c240b",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813408,
        "token_id": "674329",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Mbappe / Vietto",
        "description": "NullAddress",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674329",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/19.png",
            "address": "0x29ab976d7cd5a5c059a747575a72e4c40572540a",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813408,
        "token_id": "674329",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Aesthetic",
        "description": "Aesthetic and beautiful young woman",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674329",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/19.png",
            "address": "0x29ab976d7cd5a5c059a747575a72e4c40572540a",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },


    {
        "id": 18813404,
        "token_id": "674331",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Natasha Yi - Wild 94.9 DJ - Model",
        "description": "Natasha Yi",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674331",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/32.png",
            "address": "0x3c49f83c295b79597cb2a1820f85d8c895788775",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813403,
        "token_id": "674328",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Bean Property Writer",
        "description": "Klip snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674328",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/22.png",
            "address": "0xaa91b38a31e4b1d8955591ab040ba033449c240b",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813408,
        "token_id": "674329",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Mbappe / Vietto",
        "description": "NullAddress",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674329",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/19.png",
            "address": "0x29ab976d7cd5a5c059a747575a72e4c40572540a",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813408,
        "token_id": "674329",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Aesthetic",
        "description": "Aesthetic and beautiful young woman",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674329",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/19.png",
            "address": "0x29ab976d7cd5a5c059a747575a72e4c40572540a",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },


    {
        "id": 18813404,
        "token_id": "674331",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Natasha Yi - Wild 94.9 DJ - Model",
        "description": "Natasha Yi",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674331",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/32.png",
            "address": "0x3c49f83c295b79597cb2a1820f85d8c895788775",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813403,
        "token_id": "674328",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Bean Property Writer",
        "description": "Klip snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674328",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/22.png",
            "address": "0xaa91b38a31e4b1d8955591ab040ba033449c240b",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813408,
        "token_id": "674329",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Mbappe / Vietto",
        "description": "NullAddress",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674329",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/19.png",
            "address": "0x29ab976d7cd5a5c059a747575a72e4c40572540a",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
    {
        "id": 18813408,
        "token_id": "674329",
        "num_sales": 0,
        "background_color": "FAEDD0",
        "image_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1",
        "image_preview_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s250",
        "image_thumbnail_url": "https://lh3.googleusercontent.com/zWc7Mcnnupt-snk3cRoqNTdCePZBNKCd9w4Ka38kiiOk2XPpVPJR1sjlZQIyDArct41Iy3kUYIC23PdOIRnwF9A1=s128",
        "image_original_url": "https://media.klipwallet.com/card_asset/card_welcome_klip.png",
        "animation_url": null,
        "animation_original_url": null,
        "name": "Aesthetic",
        "description": "Aesthetic and beautiful young woman",
        "external_link": null,
        "asset_contract": {
            "address": "0xb26e09db6656b998d2913f13870e06c151c37900",
            "asset_contract_type": "non-fungible",
            "created_date": "2020-12-18T07:40:18.207092",
            "name": null,
            "nft_version": null,
            "opensea_version": null,
            "owner": null,
            "schema_name": "ERC721",
            "symbol": "",
            "total_supply": null,
            "description": null,
            "external_link": null,
            "image_url": null,
            "default_to_fiat": false,
            "dev_buyer_fee_basis_points": 0,
            "dev_seller_fee_basis_points": 0,
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": 0,
            "opensea_seller_fee_basis_points": 250,
            "buyer_fee_basis_points": 0,
            "seller_fee_basis_points": 250,
            "payout_address": null
        },
        "owner": {
            "user": {
                "username": "NullAddress"
            },
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/1.png",
            "address": "0x0000000000000000000000000000000000000000",
            "config": "",
            "discord_id": ""
        },
        "permalink": "https://opensea.io/assets/0xb26e09db6656b998d2913f13870e06c151c37900/674329",
        "collection": {
            "banner_image_url": null,
            "chat_url": null,
            "created_date": "2020-12-18T07:40:19.294596",
            "default_to_fiat": false,
            "description": null,
            "dev_buyer_fee_basis_points": "0",
            "dev_seller_fee_basis_points": "0",
            "discord_url": null,
            "display_data": {
                "card_display_style": "contain",
                "images": []
            },
            "external_url": null,
            "featured": false,
            "featured_image_url": null,
            "hidden": true,
            "safelist_request_status": "not_requested",
            "image_url": null,
            "is_subject_to_whitelist": false,
            "large_image_url": null,
            "medium_username": null,
            "name": "Klip",
            "only_proxied_transfers": false,
            "opensea_buyer_fee_basis_points": "0",
            "opensea_seller_fee_basis_points": "250",
            "payout_address": null,
            "require_email": false,
            "short_description": null,
            "slug": "klip",
            "telegram_url": null,
            "twitter_username": null,
            "instagram_username": null,
            "wiki_url": null
        },
        "decimals": null,
        "sell_orders": [],
        "creator": {
            "user": null,
            "profile_img_url": "https://storage.googleapis.com/opensea-static/opensea-profile/19.png",
            "address": "0x29ab976d7cd5a5c059a747575a72e4c40572540a",
            "config": "",
            "discord_id": ""
        },
        "traits": [
            {
                "trait_type": "사용 방법",
                "value": "지갑에 보유하고 있는 것만으로도 Klip이 준비한 깜짝 혜택의 주인공이 될 수 있습니다.",
                "display_type": null,
                "max_value": null,
                "trait_count": 436415,
                "order": null
            }
        ],
        "last_sale": null,
        "top_bid": null,
        "listing_date": null,
        "is_presale": false,
        "transfer_fee_payment_token": null,
        "transfer_fee": null
    },
];
// GET DATA
mock.onGet("/api/assets").reply(200, assets)