import mock from "../mock";

const collections = [
    {
        "primary_asset_contracts": [],
        "traits": {},
        "stats": {
            "seven_day_volume": 0.0,
            "total_volume": 0.0,
            "seven_day_change": 0.0,
            "seven_day_sales": 0.0,
            "total_sales": 0.0,
            "total_supply": 0.0,
            "count": 0.0,
            "num_owners": 0,
            "seven_day_average_price": 0.0,
            "average_price": 0.0,
            "market_cap": 0.0
        },
        "banner_image_url": null,
        "chat_url": null,
        "created_date": "2021-03-04T07:59:15.637343",
        "default_to_fiat": false,
        "description": "Your favorite entry-level monster.",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {"card_display_style": "contain"},
        "external_url": "http://cryptoslimes.co",
        "featured": false,
        "featured_image_url": null,
        "hidden": true,
        "safelist_request_status": "not_requested",
        "image_url": "https://lh3.googleusercontent.com/VJiJ3qg6cD42GqCkPmXeGq7J9AaIPEtU1rQYZBonFn1ugdbfQSiWI8-71mLMPDzFKYdmDSEW_pt_DvaWSplzW5Spkr7d6EoZUBeb=s120",
        "is_subject_to_whitelist": false,
        "large_image_url": null,
        "medium_username": null,
        "name": "CryptoSlimes",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "cryptoslimes",
        "telegram_url": null,
        "twitter_username": "thecryptoslimes",
        "instagram_username": null,
        "wiki_url": null
    },
    {
        "primary_asset_contracts": [],
        "traits": {},
        "stats": {
            "seven_day_volume": 0.0,
            "total_volume": 0.0,
            "seven_day_change": 0.0,
            "seven_day_sales": 0.0,
            "total_sales": 0.0,
            "total_supply": 0.0,
            "count": 0.0,
            "num_owners": 0,
            "seven_day_average_price": 0.0,
            "average_price": 0.0,
            "market_cap": 0.0
        },
        "banner_image_url": null,
        "chat_url": null,
        "created_date": "2021-03-04T07:58:44.745543",
        "default_to_fiat": false,
        "description": "",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {"card_display_style": "contain"},
        "external_url": null,
        "featured": false,
        "featured_image_url": null,
        "hidden": true,
        "safelist_request_status": "not_requested",
        "image_url": "https://lh3.googleusercontent.com/sVx5YzR-Bv-Lc8glwcfJLzOdOnBzsAKatWFQt4kyjVwf3c7eUt1BY-ke0gwvJkzhY565nTn6IPtE_QG6PlRyrAal0SGSox8gx5Eybw=s120",
        "is_subject_to_whitelist": false,
        "large_image_url": null,
        "medium_username": null,
        "name": "art world",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "art-world",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null
    },
    {
        "primary_asset_contracts": [],
        "traits": {},
        "stats": {
            "seven_day_volume": 0.0,
            "total_volume": 0.0,
            "seven_day_change": 0.0,
            "seven_day_sales": 0.0,
            "total_sales": 0.0,
            "total_supply": 3.0,
            "count": 3.0,
            "num_owners": 1,
            "seven_day_average_price": 0.0,
            "average_price": 0.0,
            "market_cap": 0.0
        },
        "banner_image_url": null,
        "chat_url": null,
        "created_date": "2021-03-04T07:58:25.613700",
        "default_to_fiat": false,
        "description": "A collection tackling different crystal inspirations.",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {"card_display_style": "contain", "images": []},
        "external_url": null,
        "featured": false,
        "featured_image_url": null,
        "hidden": true,
        "safelist_request_status": "not_requested",
        "image_url": "https://lh3.googleusercontent.com/imz5hhMnfaNttRQnOMeoT16rztDWx2Y8UWO-AVkUShwS92RLkeMR-1_79rDUcvQVaRM6qu0hMgV3hQ6Ceudepz36bzy_Qt9n3Nhh5g=s120",
        "is_subject_to_whitelist": false,
        "large_image_url": null,
        "medium_username": null,
        "name": "Crystal Skull Collection",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "crystal-skull-collection",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null
    },
    {
        "primary_asset_contracts": [],
        "traits": {},
        "stats": {
            "seven_day_volume": 0.0,
            "total_volume": 0.0,
            "seven_day_change": 0.0,
            "seven_day_sales": 0.0,
            "total_sales": 0.0,
            "total_supply": 1.0,
            "count": 1.0,
            "num_owners": 1,
            "seven_day_average_price": 0.0,
            "average_price": 0.0,
            "market_cap": 0.0
        },
        "banner_image_url": "https://lh3.googleusercontent.com/e2RygBYNgXpPbw3bkTqY8qU5PH1Qg0QYMqsxOPesdF8Prrb8ReQJkDE_Swkq07rc2xWFcDSsFmgIUewgIqzpz1j4N8Fnn-n8ysDE=s2500",
        "chat_url": null,
        "created_date": "2021-03-04T07:58:13.160312",
        "default_to_fiat": false,
        "description": "Dont' Panic, Be Happy",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "500",
        "discord_url": null,
        "display_data": {"card_display_style": "contain"},
        "external_url": null,
        "featured": false,
        "featured_image_url": "https://lh3.googleusercontent.com/e2RygBYNgXpPbw3bkTqY8qU5PH1Qg0QYMqsxOPesdF8Prrb8ReQJkDE_Swkq07rc2xWFcDSsFmgIUewgIqzpz1j4N8Fnn-n8ysDE=s300",
        "hidden": true,
        "safelist_request_status": "requested",
        "image_url": "https://lh3.googleusercontent.com/tQy06YjGnktpI1rXDKNZ9zqEbJTJ9Df2s0bo0fmG6Jw99gzyLFhanyMvntWyfEj5n2t-6ROX0NE_fEjFLnR80Zh70PTiViHbP7-MaQ=s120",
        "is_subject_to_whitelist": false,
        "large_image_url": "https://lh3.googleusercontent.com/e2RygBYNgXpPbw3bkTqY8qU5PH1Qg0QYMqsxOPesdF8Prrb8ReQJkDE_Swkq07rc2xWFcDSsFmgIUewgIqzpz1j4N8Fnn-n8ysDE=s300",
        "medium_username": null,
        "name": "Koro Koro",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": "0x604175636556e60faab3415dcaae943b3b0cf5fa",
        "require_email": false,
        "short_description": null,
        "slug": "koro-koro",
        "telegram_url": "https://t.me/Xuankoko",
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null
    },
    {
        "primary_asset_contracts": [],
        "traits": {},
        "stats": {
            "seven_day_volume": 0.0,
            "total_volume": 0.0,
            "seven_day_change": 0.0,
            "seven_day_sales": 0.0,
            "total_sales": 0.0,
            "total_supply": 1.0,
            "count": 1.0,
            "num_owners": 1,
            "seven_day_average_price": 0.0,
            "average_price": 0.0,
            "market_cap": 0.0
        },
        "banner_image_url": null,
        "chat_url": null,
        "created_date": "2021-03-04T07:57:43.442945",
        "default_to_fiat": false,
        "description": "rio's best creations\nNFT for sale",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {"card_display_style": "contain", "images": []},
        "external_url": null,
        "featured": false,
        "featured_image_url": null,
        "hidden": true,
        "safelist_request_status": "not_requested",
        "image_url": "https://lh3.googleusercontent.com/gzf7XhZ9uU2ozmQ7FbzZIDtwlVO2NBvRGlI9kYUVx9emhXbINHLQHCc7ybmCV3vUOftw-m5JjMcfaAnDmdLdVljKkf0mXR8W5unL=s120",
        "is_subject_to_whitelist": false,
        "large_image_url": null,
        "medium_username": null,
        "name": "rio's best",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "rio-s-best",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null
    },
    {
        "primary_asset_contracts": [],
        "traits": {},
        "stats": {
            "seven_day_volume": 0.0,
            "total_volume": 0.0,
            "seven_day_change": 0.0,
            "seven_day_sales": 0.0,
            "total_sales": 0.0,
            "total_supply": 2.0,
            "count": 2.0,
            "num_owners": 1,
            "seven_day_average_price": 0.0,
            "average_price": 0.0,
            "market_cap": 0.0
        },
        "banner_image_url": null,
        "chat_url": null,
        "created_date": "2021-03-04T07:57:23.952091",
        "default_to_fiat": false,
        "description": "colección de cestas",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {"card_display_style": "contain"},
        "external_url": null,
        "featured": false,
        "featured_image_url": null,
        "hidden": true,
        "safelist_request_status": "not_requested",
        "image_url": "https://lh3.googleusercontent.com/ohGPDK-owZPOa95vHTsNSWVkaNdYPB_R3m-dYh_8ayESSPQI8qtV2_x8S5HJ_Ats-qxYfzzSWSJByik1JAVMoi7FtV56KYbWn1rLiw=s120",
        "is_subject_to_whitelist": false,
        "large_image_url": null,
        "medium_username": null,
        "name": "La Cestita",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "la-cestita",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null
    },
    {
        "primary_asset_contracts": [],
        "traits": {},
        "stats": {
            "seven_day_volume": 0.0,
            "total_volume": 0.0,
            "seven_day_change": 0.0,
            "seven_day_sales": 0.0,
            "total_sales": 0.0,
            "total_supply": 0.0,
            "count": 0.0,
            "num_owners": 0,
            "seven_day_average_price": 0.0,
            "average_price": 0.0,
            "market_cap": 0.0
        },
        "banner_image_url": null,
        "chat_url": null,
        "created_date": "2021-03-04T07:57:23.592695",
        "default_to_fiat": false,
        "description": "nfts related images of apple",
        "dev_buyer_fee_basis_points": "0",
        "dev_seller_fee_basis_points": "0",
        "discord_url": null,
        "display_data": {"card_display_style": "contain", "images": []},
        "external_url": null,
        "featured": false,
        "featured_image_url": null,
        "hidden": true,
        "safelist_request_status": "not_requested",
        "image_url": "https://lh3.googleusercontent.com/zheZlrW4V8JUkNnvRSsTjC0FLfZZJ6LicPFFpx5husc0UW_x_H-g0zc1KYgJJUZTSacwp6wLDItNEMW6AMoBVY7YWAjm5u2k8hFI6Q=s120",
        "is_subject_to_whitelist": false,
        "large_image_url": null,
        "medium_username": null,
        "name": "apple V8",
        "only_proxied_transfers": false,
        "opensea_buyer_fee_basis_points": "0",
        "opensea_seller_fee_basis_points": "250",
        "payout_address": null,
        "require_email": false,
        "short_description": null,
        "slug": "apple-v8",
        "telegram_url": null,
        "twitter_username": null,
        "instagram_username": null,
        "wiki_url": null
    }
];


// get collections
mock.onGet("/api/collections").reply(200, collections)